skillMetadata:
  sections:
    - name: Configuration
      fields:
        - name: default_source
          type: select
          label: Default source of music
          options: "Music Library|music library;Spotify|spotify"
          value: "music library"
        - name: link_code
          type: text
          label: Link code
          value: ""
