skillMetadata:
  sections:
    - name: Configuration
      fields:
        - name: default_music_service
          type: select
          label: Default source of music
          options: "Spotify|Spotify;Amazon Music|Amazon Music;Music Library|music_library"
          value: "music_library"
