skillMetadata:
  sections:
    - name: Configuration
      fields:
        - name: default_music_service
          type: select
          label: Default source of music
          options: "Amazon Music|Amazon Music;Music Library|music_library;Spotify|Spotify"
          value: "music_library"
